name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # This is where you place your autograding tests
      # For more information on this runner, see the documentation at: https://github.com/classroom-resources/autograding-io-grader
      #
      # For example, you could run a test suite like this:
    - name: A command test
      id: main-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: A command test
        setup-command: ""
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
      # To output the results of the tests, you can use the
      # autograding-grading-reporter action like this:
      env:
        MAIN-TEST_RESULTS: "${{ steps.main-test.outputs.result }}"
      with:
          runners: main-test
